// Icon adapter: the whole app keeps importing its familiar (ex-lucide) icon
// names, mapped here to the nearest Phosphor glyph. Phosphor gives Byblos a
// rounded, multi-weight, SF-adjacent look that is MIT-licensed and shippable on
// web + Android (Apple’s SF Symbols are not). One place to remap, not 132 files.
export {
  Pulse as Activity,
  WarningCircle as AlertCircle,
  Warning as AlertTriangle,
  ArrowDownRight,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Medal as Award,
  CurrencyCircleDollar as BadgeDollarSign,
  ChartBar as BarChart3,
  Bell,
  Calendar,
  CalendarCheck as CalendarClock,
  Check,
  Checks as CheckCheck,
  CheckCircle,
  CheckCircle as CheckCircle2,
  CaretDown as ChevronDown,
  CaretLeft as ChevronLeft,
  CaretRight as ChevronRight,
  CaretUp as ChevronUp,
  Circle,
  Clock,
  Copy,
  CreditCard,
  CurrencyDollar as DollarSign,
  DownloadSimple as Download,
  PencilSimple as Edit,
  Pencil as Edit2,
  PencilLine as Edit3,
  ArrowSquareOut as ExternalLink,
  Eye,
  EyeSlash as EyeOff,
  FacebookLogo as Facebook,
  FileText,
  Globe,
  Handshake,
  Heart,
  ClockCounterClockwise as History,
  House as Home,
  Image,
  ImageSquare as ImagePlus,
  Info,
  InstagramLogo as Instagram,
  Key as KeyRound,
  SquaresFour as LayoutDashboard,
  LinkSimple as Link2,
  CircleNotch as Loader2,
  Lock,
  SignOut as LogOut,
  Envelope as Mail,
  EnvelopeSimple as MailPlus,
  MapPin,
  Megaphone,
  List as Menu,
  ChatCircle as MessageCircle,
  ChatText as MessageSquare,
  Minus,
  Moon,
  DotsThreeVertical as MoreVertical,
  CursorClick as MousePointerClick,
  MusicNote as Music2,
  NavigationArrow as Navigation,
  Package,
  Package as PackageCheck,
  Package as PackagePlus,
  Package as PackageSearch,
  Palette,
  PencilSimple as Pencil,
  Percent,
  Phone,
  Plus,
  ArrowsClockwise as RefreshCw,
  MagnifyingGlass as Search,
  PaperPlaneTilt as Send,
  GearSix as Settings,
  ShareNetwork as Share2,
  Shield,
  ShieldWarning as ShieldAlert,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Sparkle as Sparkles,
  Storefront as Store,
  Sun,
  Trash as Trash2,
  TrendUp as TrendingUp,
  Truck,
  ArrowUUpLeft as Undo2,
  CloudArrowUp as UploadCloud,
  User,
  UserCircle,
  UserMinus,
  UserPlus,
  User as UserRound,
  UserFocus as UserRoundPen,
  Users,
  Users as Users2,
  Wallet,
  Wallet as WalletCards,
  X,
  XCircle,
} from '@phosphor-icons/react';

// Ex-lucide `LucideIcon` prop type -> Phosphor's component type.
export type { Icon as LucideIcon } from '@phosphor-icons/react';
